[tool.black]
line-length = 120
target-version = ['py311']
include = '\\.pyi?$'

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
warn_return_any = true
warn_unused_configs = true

[tool.pytest.ini_options]
minversion = "7.0"
adopts = "-ra -q"
testpaths = [
    "tests"
]
